catalogs:
    vite:
        vite: 8.0.0-beta.8
    drizzle:
        drizzle-kit: 1.0.0-beta.11-05230d9
        drizzle-orm: 1.0.0-beta.11-05230d9

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@jderstd/hono"
    - "@jderstd/hono-openapi"
    - "ts-vista"
    - "vitend"
