catalogs:
    vite:
        vite: 8.0.0-beta.8

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@jderstd/hono"
    - "@jderstd/hono-openapi"
    - "ts-vista"
    - "vitend"
